[mypy]
python_version = 3.13
mypy_path = apps/api/src
namespace_packages = True
explicit_package_bases = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
disallow_untyped_defs = True
plugins = pydantic.mypy

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-casbin.*]
ignore_missing_imports = True
