"""principals audit and review

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-09 22:21:03.012229

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_principal_id', sa.Uuid(), nullable=False),
    sa.Column('delegate_principal_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decision', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('policy_hash', sa.String(), nullable=False),
    sa.Column('grant_revision', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_principal_issuer_subject')
    )
    op.create_table('review_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assembled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assembling_principal_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('grant_revision', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assertion_id', sa.Uuid(), nullable=False),
    sa.Column('assertion_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('review_batch_id', sa.Uuid(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['assertion.id'], ),
    sa.ForeignKeyConstraint(['review_batch_id'], ['review_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_item_id', sa.Uuid(), nullable=False),
    sa.Column('review_batch_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('corrected_assertion_id', sa.Uuid(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('reviewer_principal_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_comment', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assertion_version', sa.Integer(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('event_sha256', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_assertion_id'], ['assertion.id'], ),
    sa.ForeignKeyConstraint(['review_batch_id'], ['review_batch.id'], ),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_item_id', 'event_sha256', name='uq_review_decision_item_event')
    )
    op.add_column('assertion', sa.Column('origin', sa.String(), nullable=False))
    op.add_column('assertion', sa.Column('original_assertion_id', sa.Uuid(), nullable=True))
    op.add_column('assertion', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('assertion', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_assertion_original_assertion_id', 'assertion', 'assertion', ['original_assertion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assertion_original_assertion_id', 'assertion', type_='foreignkey')
    op.alter_column('assertion', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('assertion', 'version')
    op.drop_column('assertion', 'original_assertion_id')
    op.drop_column('assertion', 'origin')
    op.drop_table('review_decision')
    op.drop_table('review_item')
    op.drop_table('membership')
    op.drop_table('review_batch')
    op.drop_table('principal')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
