"""fact slots and commits

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-10 10:50:33.951278

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_slot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('slot_type', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_fact_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('valid', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('recorded', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('review_decision_id', sa.Uuid(), nullable=True),
    sa.Column('commit_id', sa.Uuid(), nullable=False),
    sa.Column('source_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artifact_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assertion_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canonical_accepted_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.column('slot_id'), '='), (sa.column('valid'), '&&'), (sa.column('recorded'), '&&'), using='gist', name='excl_canonical_fact_version_slot_valid_recorded'),
    sa.ForeignKeyConstraint(['slot_id'], ['fact_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_fact_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('from_version_id', sa.Uuid(), nullable=True),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_version_id'], ['canonical_fact_version.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['canonical_fact_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canonical_fact_change')
    op.drop_table('canonical_fact_version')
    op.drop_table('outbox_event')
    op.drop_table('fact_slot')
    # ### end Alembic commands ###
